name: Sync Docs to ReadMe and Consumers

on:
  push:
    paths:
      - 'docs/**'  # Trigger when /docs changes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set the correct target branch
        id: get_branch
        run: |
          echo "TARGET_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Push to ReadMe Docs
        uses: cpina/github-action-push-to-another-repository@v1
        with:
          source-directory: 'docs'
          destination-github-username: 'algol22'
          destination-repository-name: 'readme-docs'
          user-email: 'andriyslb@gmail.com'
          target-branch: ${{ env.TARGET_BRANCH }}  # Dynamically set branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN }}

      - name: Push to Consumer A
        uses: cpina/github-action-push-to-another-repository@v1
        with:
          source-directory: 'docs'
          destination-github-username: 'algol22'
          destination-repository-name: 'readme-consumer-a'
          user-email: 'andriyslb@gmail.com'
          target-branch: ${{ env.TARGET_BRANCH }}  # Dynamically set branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN }}

      - name: Push to Consumer B
        uses: cpina/github-action-push-to-another-repository@v1
        with:
          source-directory: 'docs'
          destination-github-username: 'algol22'
          destination-repository-name: 'readme-consumer-b'
          user-email: 'andriyslb@gmail.com'
          target-branch: ${{ env.TARGET_BRANCH }}  # Dynamically set branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN }}
